### ISSUE TITLE
Extension Fails Silently When Unknown Syntax

### ISSUE THREAD

**Issue by zsteiner** [mfeckie/handlebars-formatter#9] opened 2019-07-09 18:20 UTC
When the formatter encounters Handlebars syntax that it doesn't support. The extension doesn't format any part of the file. For example, nested partials don't seem to be supported:

`{{#>wrapper}}<h1>Title</h1>{{/wrapper}}`

In cases such as this, the entire file is ignored and Format Selection for unrelated parts of the file fail silently as well.

**Comment by mfeckie** [comment] 2019-07-10 00:35
Yeah, unless it's supported by the prettier parser for `glimmer` it's not supported in this extension.

I'm gonna close this because it's a problem outside of this extension's control.

I'd recommend opening an issue with the folks at Prettier.

**Closed as completed by mfeckie** 2019-07-10 00:35 UTC

**Comment by zsteiner** [comment] 2019-07-10 01:05
I completely understand and will file the specific issue with prettier. I should have been more clear that the issue is the extension failing silently. I thought the extension was broken for some time. Appreciate the follow up!

**Comment by mfeckie** [comment] 2019-07-10 01:11
Yeah the problem is that the `glimmer` parser for prettier remains unreleased and is therefore not really well supported.  The reason it fails silently is over-caution on my part.  Basically I'm not sure of all the ways it can fail and what to do, so I chose just to handle that quietly.

Once prettier supports glimmer out of the box, this extension is probably redundant, so I'm not sure that putting extra work into it is beneficial.

Having said that, if you wanted to poke at it and submit a PR, then I'd happily consider it 😄
